apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mijn-website
      version: green
  template:
    metadata:
      labels:
        app: mijn-website
        version: green
    spec:
      containers:
      - name: webserver
        image: IMAGE_PLACEHOLDER 
        ports:
        - containerPort: 80