name: Build and Deploy to GKE

# Deze pipeline draait alleen als je iets pusht naar de main branch
on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ vars.GKE_PROJECT }}
  GAR_LOCATION: ${{ vars.GAR_LOCATION }}
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_ZONE: ${{ vars.GKE_ZONE }}
  DEPLOYMENT_NAME: website-blue
  REPOSITORY: assignment2 # Verander dit naar de naam van jouw Artifact Registry!
  IMAGE: mijn-website

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # 1. INLOGGEN BIJ GOOGLE CLOUD
    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Use gcloud CLI
      run: gcloud info

    - name: Docker auth
      run: |-
        gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev

    - name: Get GKE credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}

    # 2. BOUWEN EN PUSHEN NAAR ARTIFACT REGISTRY
    - name: Build and Push Docker image
      run: |-
        docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}" .
        docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}"

    # 3. DEPLOYEN NAAR KUBERNETES
    - name: Set up Kustomize (tool om yaml aan te passen)
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy to GKE
      run: |-
        # Vervang de IMAGE_PLACEHOLDER met de echte image link
        sed -i "s|IMAGE_PLACEHOLDER|${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.sha }}|g" k8s/deployment.yaml
        
        # Stuur de yaml bestanden naar het cluster
        kubectl apply -f kubernetes/deployment.yaml
        kubectl apply -f kubernetes/service.yaml